In [ ]:
#Matrizes

In [4]:
import numpy as np

In [6]:
M = np.array([[1,2,3],[3,4,5],[6,7,8]])

In [7]:
M

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
type(M)

numpy.ndarray

In [9]:
H2 = np.matrix([[1,2,3],[3,4,5],[6,7,8]])

In [10]:
H2

matrix([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [11]:
type (H2)

numpy.matrix

In [12]:
M[1,1]

4

In [13]:
M[1,0]

3

In [14]:
M[:,2]

array([3, 5, 8])

In [15]:
M[1,:]

array([3, 4, 5])

In [16]:
M[0,:]

array([1, 2, 3])